// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: sayhello/service/v1/sayhello.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSayhelloHelloProxy = "/sayhello.v1.Sayhello/HelloProxy"
const OperationSayhelloSayHello = "/sayhello.v1.Sayhello/SayHello"

type SayhelloHTTPServer interface {
	// HelloProxy Proxies a greeting request to the helloworld service via gRPC
	HelloProxy(context.Context, *HelloProxyRequest) (*HelloProxyReply, error)
	// SayHello Sends a greeting
	SayHello(context.Context, *SayhelloRequest) (*SayhelloReply, error)
}

func RegisterSayhelloHTTPServer(s *http.Server, srv SayhelloHTTPServer) {
	r := s.Route("/")
	r.GET("/sayhello/{name}", _Sayhello_SayHello0_HTTP_Handler(srv))
	r.GET("/hello/{name}", _Sayhello_HelloProxy0_HTTP_Handler(srv))
}

func _Sayhello_SayHello0_HTTP_Handler(srv SayhelloHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayhelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSayhelloSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*SayhelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayhelloReply)
		return ctx.Result(200, reply)
	}
}

func _Sayhello_HelloProxy0_HTTP_Handler(srv SayhelloHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloProxyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSayhelloHelloProxy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HelloProxy(ctx, req.(*HelloProxyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloProxyReply)
		return ctx.Result(200, reply)
	}
}

type SayhelloHTTPClient interface {
	// HelloProxy Proxies a greeting request to the helloworld service via gRPC
	HelloProxy(ctx context.Context, req *HelloProxyRequest, opts ...http.CallOption) (rsp *HelloProxyReply, err error)
	// SayHello Sends a greeting
	SayHello(ctx context.Context, req *SayhelloRequest, opts ...http.CallOption) (rsp *SayhelloReply, err error)
}

type SayhelloHTTPClientImpl struct {
	cc *http.Client
}

func NewSayhelloHTTPClient(client *http.Client) SayhelloHTTPClient {
	return &SayhelloHTTPClientImpl{client}
}

// HelloProxy Proxies a greeting request to the helloworld service via gRPC
func (c *SayhelloHTTPClientImpl) HelloProxy(ctx context.Context, in *HelloProxyRequest, opts ...http.CallOption) (*HelloProxyReply, error) {
	var out HelloProxyReply
	pattern := "/hello/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSayhelloHelloProxy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SayHello Sends a greeting
func (c *SayhelloHTTPClientImpl) SayHello(ctx context.Context, in *SayhelloRequest, opts ...http.CallOption) (*SayhelloReply, error) {
	var out SayhelloReply
	pattern := "/sayhello/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSayhelloSayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
