// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: sayhello/service/v1/sayhello.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SayhelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayhelloRequest) Reset() {
	*x = SayhelloRequest{}
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayhelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayhelloRequest) ProtoMessage() {}

func (x *SayhelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayhelloRequest.ProtoReflect.Descriptor instead.
func (*SayhelloRequest) Descriptor() ([]byte, []int) {
	return file_sayhello_service_v1_sayhello_proto_rawDescGZIP(), []int{0}
}

func (x *SayhelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SayhelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayhelloReply) Reset() {
	*x = SayhelloReply{}
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayhelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayhelloReply) ProtoMessage() {}

func (x *SayhelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayhelloReply.ProtoReflect.Descriptor instead.
func (*SayhelloReply) Descriptor() ([]byte, []int) {
	return file_sayhello_service_v1_sayhello_proto_rawDescGZIP(), []int{1}
}

func (x *SayhelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloProxyRequest) Reset() {
	*x = HelloProxyRequest{}
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloProxyRequest) ProtoMessage() {}

func (x *HelloProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloProxyRequest.ProtoReflect.Descriptor instead.
func (*HelloProxyRequest) Descriptor() ([]byte, []int) {
	return file_sayhello_service_v1_sayhello_proto_rawDescGZIP(), []int{2}
}

func (x *HelloProxyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloProxyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloProxyReply) Reset() {
	*x = HelloProxyReply{}
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloProxyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloProxyReply) ProtoMessage() {}

func (x *HelloProxyReply) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_service_v1_sayhello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloProxyReply.ProtoReflect.Descriptor instead.
func (*HelloProxyReply) Descriptor() ([]byte, []int) {
	return file_sayhello_service_v1_sayhello_proto_rawDescGZIP(), []int{3}
}

func (x *HelloProxyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sayhello_service_v1_sayhello_proto protoreflect.FileDescriptor

const file_sayhello_service_v1_sayhello_proto_rawDesc = "" +
	"\n" +
	"\"sayhello/service/v1/sayhello.proto\x12\vsayhello.v1\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\x0fSayhelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rSayhelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x11HelloProxyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x0fHelloProxyReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcd\x01\n" +
	"\bSayhello\x12^\n" +
	"\bSayHello\x12\x1c.sayhello.v1.SayhelloRequest\x1a\x1a.sayhello.v1.SayhelloReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/sayhello/{name}\x12a\n" +
	"\n" +
	"HelloProxy\x12\x1e.sayhello.v1.HelloProxyRequest\x1a\x1c.sayhello.v1.HelloProxyReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/hello/{name}B\x1cZ\x1aapi/sayhello/service/v1;v1b\x06proto3"

var (
	file_sayhello_service_v1_sayhello_proto_rawDescOnce sync.Once
	file_sayhello_service_v1_sayhello_proto_rawDescData []byte
)

func file_sayhello_service_v1_sayhello_proto_rawDescGZIP() []byte {
	file_sayhello_service_v1_sayhello_proto_rawDescOnce.Do(func() {
		file_sayhello_service_v1_sayhello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sayhello_service_v1_sayhello_proto_rawDesc), len(file_sayhello_service_v1_sayhello_proto_rawDesc)))
	})
	return file_sayhello_service_v1_sayhello_proto_rawDescData
}

var file_sayhello_service_v1_sayhello_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sayhello_service_v1_sayhello_proto_goTypes = []any{
	(*SayhelloRequest)(nil),   // 0: sayhello.v1.SayhelloRequest
	(*SayhelloReply)(nil),     // 1: sayhello.v1.SayhelloReply
	(*HelloProxyRequest)(nil), // 2: sayhello.v1.HelloProxyRequest
	(*HelloProxyReply)(nil),   // 3: sayhello.v1.HelloProxyReply
}
var file_sayhello_service_v1_sayhello_proto_depIdxs = []int32{
	0, // 0: sayhello.v1.Sayhello.SayHello:input_type -> sayhello.v1.SayhelloRequest
	2, // 1: sayhello.v1.Sayhello.HelloProxy:input_type -> sayhello.v1.HelloProxyRequest
	1, // 2: sayhello.v1.Sayhello.SayHello:output_type -> sayhello.v1.SayhelloReply
	3, // 3: sayhello.v1.Sayhello.HelloProxy:output_type -> sayhello.v1.HelloProxyReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sayhello_service_v1_sayhello_proto_init() }
func file_sayhello_service_v1_sayhello_proto_init() {
	if File_sayhello_service_v1_sayhello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sayhello_service_v1_sayhello_proto_rawDesc), len(file_sayhello_service_v1_sayhello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sayhello_service_v1_sayhello_proto_goTypes,
		DependencyIndexes: file_sayhello_service_v1_sayhello_proto_depIdxs,
		MessageInfos:      file_sayhello_service_v1_sayhello_proto_msgTypes,
	}.Build()
	File_sayhello_service_v1_sayhello_proto = out.File
	file_sayhello_service_v1_sayhello_proto_goTypes = nil
	file_sayhello_service_v1_sayhello_proto_depIdxs = nil
}
