// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: sayhello/service/v1/sayhello.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sayhello_SayHello_FullMethodName   = "/sayhello.v1.Sayhello/SayHello"
	Sayhello_HelloProxy_FullMethodName = "/sayhello.v1.Sayhello/HelloProxy"
)

// SayhelloClient is the client API for Sayhello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type SayhelloClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *SayhelloRequest, opts ...grpc.CallOption) (*SayhelloReply, error)
	// Proxies a greeting request to the helloworld service via gRPC
	HelloProxy(ctx context.Context, in *HelloProxyRequest, opts ...grpc.CallOption) (*HelloProxyReply, error)
}

type sayhelloClient struct {
	cc grpc.ClientConnInterface
}

func NewSayhelloClient(cc grpc.ClientConnInterface) SayhelloClient {
	return &sayhelloClient{cc}
}

func (c *sayhelloClient) SayHello(ctx context.Context, in *SayhelloRequest, opts ...grpc.CallOption) (*SayhelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayhelloReply)
	err := c.cc.Invoke(ctx, Sayhello_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayhelloClient) HelloProxy(ctx context.Context, in *HelloProxyRequest, opts ...grpc.CallOption) (*HelloProxyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloProxyReply)
	err := c.cc.Invoke(ctx, Sayhello_HelloProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayhelloServer is the server API for Sayhello service.
// All implementations must embed UnimplementedSayhelloServer
// for forward compatibility.
//
// The greeting service definition.
type SayhelloServer interface {
	// Sends a greeting
	SayHello(context.Context, *SayhelloRequest) (*SayhelloReply, error)
	// Proxies a greeting request to the helloworld service via gRPC
	HelloProxy(context.Context, *HelloProxyRequest) (*HelloProxyReply, error)
	mustEmbedUnimplementedSayhelloServer()
}

// UnimplementedSayhelloServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSayhelloServer struct{}

func (UnimplementedSayhelloServer) SayHello(context.Context, *SayhelloRequest) (*SayhelloReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSayhelloServer) HelloProxy(context.Context, *HelloProxyRequest) (*HelloProxyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HelloProxy not implemented")
}
func (UnimplementedSayhelloServer) mustEmbedUnimplementedSayhelloServer() {}
func (UnimplementedSayhelloServer) testEmbeddedByValue()                  {}

// UnsafeSayhelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayhelloServer will
// result in compilation errors.
type UnsafeSayhelloServer interface {
	mustEmbedUnimplementedSayhelloServer()
}

func RegisterSayhelloServer(s grpc.ServiceRegistrar, srv SayhelloServer) {
	// If the following call panics, it indicates UnimplementedSayhelloServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sayhello_ServiceDesc, srv)
}

func _Sayhello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayhelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayhelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sayhello_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayhelloServer).SayHello(ctx, req.(*SayhelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sayhello_HelloProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayhelloServer).HelloProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sayhello_HelloProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayhelloServer).HelloProxy(ctx, req.(*HelloProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sayhello_ServiceDesc is the grpc.ServiceDesc for Sayhello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sayhello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sayhello.v1.Sayhello",
	HandlerType: (*SayhelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Sayhello_SayHello_Handler,
		},
		{
			MethodName: "HelloProxy",
			Handler:    _Sayhello_HelloProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sayhello/service/v1/sayhello.proto",
}
