apiVersion: apps/v1
kind: Deployment
metadata:
  name: sayhello
  namespace: default
  labels:
    app: sayhello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sayhello
  template:
    metadata:
      labels:
        app: sayhello
    spec:
      containers:
        - name: sayhello
          image: orbit-sayhello-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: /data/conf
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: sayhello-config
