apiVersion: v1
kind: Service
metadata:
  name: sayhello
  namespace: default
  labels:
    app: sayhello
spec:
  selector:
    app: sayhello
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
