// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ray-dota/backend-mono/app/sayhello/service/internal/biz"
	"github.com/ray-dota/backend-mono/app/sayhello/service/internal/conf"
	"github.com/ray-dota/backend-mono/app/sayhello/service/internal/data"
	"github.com/ray-dota/backend-mono/app/sayhello/service/internal/server"
	"github.com/ray-dota/backend-mono/app/sayhello/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	sayhelloRepo := data.NewSayhelloRepo(dataData, logger)
	sayhelloUsecase := biz.NewSayhelloUsecase(sayhelloRepo, logger)
	greeterClient, cleanup2, err := data.NewHelloworldClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	helloworldUsecase := biz.NewHelloworldUsecase(greeterClient, logger)
	sayhelloService := service.NewSayhelloService(sayhelloUsecase, helloworldUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, sayhelloService, logger)
	httpServer := server.NewHTTPServer(confServer, sayhelloService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
