apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: orbit-helloworld-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: /data/conf
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: helloworld-config
